title: Krpano 中文
subtitle: "Krpano 非官方中文文档"
keywords: "krpano,全景图,全景视频,全景图制作,全景视频制作,全景图制作软件,全景视频制作软件,VR,VR助手,VR制作软件,krpano教程,krpano中文教程"
description: "krpano 是一款支持全平台的全景图与全景视频制作工具，也是目前市场上用于制作VR资源的工具。本站提供 krpano 中文教程与文档。"
author: Milly Lee
language: zh-CN
timezone: UTC
url: http://krpano.milly.me
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md
post_asset_folder: true # 启用Asset文件夹
auto_spacing: true # 中文与英文之间加入空格
filename_case: 1 # 将文字名转换为小写，2为大写
highlight:
  enable: true
  line_number: false
per_page: 0

# 主题
theme: mitopic

# 部署
deploy:
  type: git
  repo: git@github.com:millylee/krpano.git
  branch: gh-pages

# 评论
comment:
  duoshuo: 99knowledge

# 统计
analytics:
  baidu: 'cb9af96e6e2fed8bd03189163e3a47b5'

# 社交
twitter: millyleecn
github: millylee